# -*- coding: utf-8 -*-


from theano.tensor import scalar
from theano.tensor import vector
from theano.tensor import row
from theano.tensor import col
from theano.tensor import matrix
from theano.tensor import tensor3
from theano.tensor import tensor4
from theano.tensor import tensor5
from theano.tensor import bscalar
from theano.tensor import bvector
from theano.tensor import brow
from theano.tensor import bcol
from theano.tensor import bmatrix
from theano.tensor import btensor3
from theano.tensor import btensor4
from theano.tensor import btensor5
from theano.tensor import wscalar
from theano.tensor import wvector
from theano.tensor import wrow
from theano.tensor import wcol
from theano.tensor import wmatrix
from theano.tensor import wtensor3
from theano.tensor import wtensor4
from theano.tensor import wtensor5
from theano.tensor import iscalar
from theano.tensor import ivector
from theano.tensor import irow
from theano.tensor import icol
from theano.tensor import imatrix
from theano.tensor import itensor3
from theano.tensor import itensor4
from theano.tensor import itensor5
from theano.tensor import lscalar
from theano.tensor import lvector
from theano.tensor import lrow
from theano.tensor import lcol
from theano.tensor import lmatrix
from theano.tensor import ltensor3
from theano.tensor import ltensor4
from theano.tensor import ltensor5
from theano.tensor import dscalar
from theano.tensor import dvector
from theano.tensor import drow
from theano.tensor import dcol
from theano.tensor import dmatrix
from theano.tensor import dtensor3
from theano.tensor import dtensor4
from theano.tensor import dtensor5
from theano.tensor import fscalar
from theano.tensor import fvector
from theano.tensor import frow
from theano.tensor import fcol
from theano.tensor import fmatrix
from theano.tensor import ftensor3
from theano.tensor import ftensor4
from theano.tensor import ftensor5
from theano.tensor import cscalar
from theano.tensor import cvector
from theano.tensor import crow
from theano.tensor import ccol
from theano.tensor import cmatrix
from theano.tensor import ctensor3
from theano.tensor import ctensor4
from theano.tensor import ctensor5
from theano.tensor import zscalar
from theano.tensor import zvector
from theano.tensor import zrow
from theano.tensor import zcol
from theano.tensor import zmatrix
from theano.tensor import ztensor3
from theano.tensor import ztensor4
from theano.tensor import ztensor5
from theano.tensor import iscalars
from theano.tensor import lscalars
from theano.tensor import fscalars
from theano.tensor import dscalars
from theano.tensor import ivectors
from theano.tensor import lvectors
from theano.tensor import fvectors
from theano.tensor import dvectors
from theano.tensor import irows
from theano.tensor import lrows
from theano.tensor import frows
from theano.tensor import drows
from theano.tensor import icols
from theano.tensor import lcols
from theano.tensor import fcols
from theano.tensor import dcols
from theano.tensor import imatrices
from theano.tensor import lmatrices
from theano.tensor import fmatrices
from theano.tensor import dmatrices


def get_tensor(tensor_type):
    return globals().get(tensor_type)


"""
from theano.tensor import scalar
from theano.tensor import vector
from theano.tensor import row
from theano.tensor import col
from theano.tensor import matrix
from theano.tensor import tensor3
from theano.tensor import tensor4
from theano.tensor import tensor5
from theano.tensor import bscalar
from theano.tensor import bvector
from theano.tensor import brow
from theano.tensor import bcol
from theano.tensor import bmatrix
from theano.tensor import btensor3
from theano.tensor import btensor4
from theano.tensor import btensor5
from theano.tensor import wscalar
from theano.tensor import wvector
from theano.tensor import wrow
from theano.tensor import wcol
from theano.tensor import wmatrix
from theano.tensor import wtensor3
from theano.tensor import wtensor4
from theano.tensor import wtensor5
from theano.tensor import iscalar
from theano.tensor import ivector
from theano.tensor import irow
from theano.tensor import icol
from theano.tensor import imatrix
from theano.tensor import itensor3
from theano.tensor import itensor4
from theano.tensor import itensor5
from theano.tensor import lscalar
from theano.tensor import lvector
from theano.tensor import lrow
from theano.tensor import lcol
from theano.tensor import lmatrix
from theano.tensor import ltensor3
from theano.tensor import ltensor4
from theano.tensor import ltensor5
from theano.tensor import dscalar
from theano.tensor import dvector
from theano.tensor import drow
from theano.tensor import dcol
from theano.tensor import dmatrix
from theano.tensor import dtensor3
from theano.tensor import dtensor4
from theano.tensor import dtensor5
from theano.tensor import fscalar
from theano.tensor import fvector
from theano.tensor import frow
from theano.tensor import fcol
from theano.tensor import fmatrix
from theano.tensor import ftensor3
from theano.tensor import ftensor4
from theano.tensor import ftensor5
from theano.tensor import cscalar
from theano.tensor import cvector
from theano.tensor import crow
from theano.tensor import ccol
from theano.tensor import cmatrix
from theano.tensor import ctensor3
from theano.tensor import ctensor4
from theano.tensor import ctensor5
from theano.tensor import zscalar
from theano.tensor import zvector
from theano.tensor import zrow
from theano.tensor import zcol
from theano.tensor import zmatrix
from theano.tensor import ztensor3
from theano.tensor import ztensor4
from theano.tensor import ztensor5
from theano.tensor import iscalars
from theano.tensor import lscalars
from theano.tensor import fscalars
from theano.tensor import dscalars
from theano.tensor import ivectors
from theano.tensor import lvectors
from theano.tensor import fvectors
from theano.tensor import dvectors
from theano.tensor import irows
from theano.tensor import lrows
from theano.tensor import frows
from theano.tensor import drows
from theano.tensor import icols
from theano.tensor import lcols
from theano.tensor import fcols
from theano.tensor import dcols
from theano.tensor import imatrices
from theano.tensor import lmatrices
from theano.tensor import fmatrices
from theano.tensor import dmatrices
"""


